export const endpoints = {
    iam: {
        users: '/api/users',
        userToken: '/realms/customer/protocol/openid-connect/token',
        adminToken: '/realms/master/protocol/openid-connect/token',
        adminUsers: '/admin/realms/customer/users',
    },
    stellare: {
        users: '/api/users',
        product: '/api/loan-products',
        processes: '/api/processes/{processId}',
        userInstance: '/api/user-instances',
        currentTask: '/api/tasks/current-task',
        tasks: '/api/tasks/{taskId}',
        taskVariables: '/api/tasks/{taskId}/variables',
        application: '/api/loan-applications',
        loanPurpose: '/api/loan-products/{productId}/loan-purposes',
        saveLoanPurpose: '/api/loan-applications/{applicationId}/loan-purposes',
        idvStartSession: '/api/identity-verifications/machine-session',
        networthSources: '/api/financial-profile/networth-sources?kind={kind}', 
        income: '/api/financial-profile/incomes',
        expense: '/api/financial-profile/expenses',
        assets: '/api/financial-profile/assets',
        liabilities: '/api/financial-profile/liabilities',
        bankConfig: '/api/bank-statement/configuration',
        userProfile: '/api/user-profile/{userId}',
        address: '/api/user-profile/address/{address}',
    },
    frankieOne: {
        tokenValidity: '/data/v2/token-validity',
        event: '/data/v1/events',
        applicant: '/data/v2/applicants/?no_address=false',
        address: '/data/v1/address/search',
        formAddress: '/data/v2/address/{addressValue}',
        applicantById: '/data/v2/applicants/{entityId}',
        checkApplicant: '/data/v1/applicants/{entityId}/checks',
    },
    proviso: {
        init: '/v1/customer/initialise/{token}',
        institution: '/v1/customer/initialise/{token}/institution',
        submitBank: '/v1/customer/initialise/{token}/validate',
        bsStatus: '/api/bank-statement/{appRef}',
    }
}