export const events: Array<string> = [
    'SCREEN:DOCUMENT_TYPE_SELECT',
    'SCREEN:DRIVERS_LICENCE_INPUT',
    'SCREEN:NAME_INPUT',
    'SCREEN:DOB_INPUT',
    'SCREEN:ADDRESS_INPUT',
    'SCREEN:MANUAL_ADDRESS_INPUT',
    'SCREEN:DETAILS_SUMMARY'
];