export enum ResidencyStatus {
    AU_CITIZEN_OR_PERMANENT_RESIDENT = 'AU_CITIZEN_OR_PERMANENT_RESIDENT',
    NZ_CITIZEN_OR_PERMANENT_RESIDENT = 'NZ_CITIZEN_OR_PERMANENT_RESIDENT',
    NONE_CITIZEN_OR_PERMANENT_RESIDENT = 'NONE_CITIZEN_OR_PERMANENT_RESIDENT',
}