export const routeMap: {[key: string]: string} = {
    "user task username": "user-task-collect-user-name",
    "user task loan-purpose": "user-task-collect-loan-purpose",
    "user task loan-amount": "user-task-collect-loan-amount",
    "user task save-progress": "user-task-sign-up",
    "user task idv-welcome": "user-task-identity-welcome",
    "user task idv-frankie-smart-ui": "user-task-identity-information",
    "user task income": "user-task-income",
    "user task living-expense": "user-task-living-expense",
    "user task household": "user-task-household",
    "user task connect-bank": "bank-statement-iframe",
    "user task load-bank-statement": "waiting-for-bank-statement",
    "user task asset": "user-task-asset",
    "user task debt": "user-task-debt",
    "user task financial-summary": "user-task-summary",
    "user task valid-quote": "user-task-valid-quote",
    "user task check-profile": "user-task-check-profile",
    "user task email-verification": "user-task-verify-email",
    "user task payment": "user-task-payment",
    "user task contract": "user-task-sign-contract"
}