export const routeMap: {[key: string]: string} = {
    "page username": "user-task-collect-user-name",
    "page loan-purpose": "user-task-collect-loan-purpose",
    "page loan-amount": "user-task-collect-loan-amount",
    "page save-progress": "user-task-sign-up",
    "page idv-welcome": "user-task-identity-welcome",
    "page idv-frankie-smart-ui": "user-task-identity-information",
    "page income": "user-task-income",
    "page living-expense": "user-task-living-expense",
    "page household": "user-task-household",
    "page connect-bank": "bank-statement-iframe",
    "page load-bank-statement": "waiting-for-bank-statement",
    "page asset": "user-task-asset",
    "page debt": "user-task-debt",
    "page financial-summary": "user-task-summary",
    "page valid-quote": "user-task-valid-quote",
    "page check-profile": "user-task-check-profile",
    "page email-verification": "user-task-verify-email",
    "page password-setup": "user-task-set-password",
    "page payment": "user-task-payment",
    "page contract": "user-task-sign-contract"
}